// Generated from https://github.com/othmanus/algeria-cities (58 wilayas, 1541 communes)
export const COMMUNES_BY_WILAYA_CODE: Record<string, { en: string; ar: string }[]> = {
  "01": [
    { en: "Adrar", ar: "أدرار" },
    { en: "Akabli", ar: "اقبلي" },
    { en: "Aoulef", ar: "أولف" },
    { en: "Bouda", ar: "بودة" },
    { en: "Fenoughil", ar: "فنوغيل" },
    { en: "In Zghmir", ar: "إن زغمير" },
    { en: "Ouled Ahmed Timmi", ar: "أولاد أحمد تيمي" },
    { en: "Reggane", ar: "رقان" },
    { en: "Sali", ar: "سالي" },
    { en: "Sebaa", ar: "السبع" },
    { en: "Tamantit", ar: "تامنطيط" },
    { en: "Tamest", ar: "تامست" },
    { en: "Timekten", ar: "تيمقتن" },
    { en: "Tit", ar: "تيت" },
    { en: "Tsabit", ar: "تسابيت" },
    { en: "Zaouiet Kounta", ar: "زاوية كنتة" },
  ],
  "02": [
    { en: "Abou El Hassane", ar: "أبو الحسن" },
    { en: "Ain Merane", ar: "عين مران" },
    { en: "Benairia", ar: "بنايرية" },
    { en: "Beni  Bouattab", ar: "بني بوعتاب" },
    { en: "Beni Haoua", ar: "بني حواء" },
    { en: "Beni Rached", ar: "بني راشد" },
    { en: "Boukadir", ar: "بوقادير" },
    { en: "Bouzeghaia", ar: "بوزغاية" },
    { en: "Breira", ar: "بريرة" },
    { en: "Chettia", ar: "الشطية" },
    { en: "Chlef", ar: "الشلف" },
    { en: "Dahra", ar: "الظهرة" },
    { en: "El Hadjadj", ar: "الحجاج" },
    { en: "El Karimia", ar: "الكريمية" },
    { en: "El Marsa", ar: "المرسى" },
    { en: "Harchoun", ar: "حرشون" },
    { en: "Herenfa", ar: "الهرانفة" },
    { en: "Labiod Medjadja", ar: "الأبيض مجاجة" },
    { en: "Moussadek", ar: "مصدق" },
    { en: "Oued Fodda", ar: "وادي الفضة" },
    { en: "Oued Goussine", ar: "وادي قوسين" },
    { en: "Oued Sly", ar: "وادي سلي" },
    { en: "Ouled Abbes", ar: "أولاد عباس" },
    { en: "Ouled Ben Abdelkader", ar: "أولاد بن عبد القادر" },
    { en: "Ouled Fares", ar: "أولاد فارس" },
    { en: "Oum Drou", ar: "أم الدروع" },
    { en: "Sendjas", ar: "سنجاس" },
    { en: "Sidi Abderrahmane", ar: "سيدي عبد الرحمن" },
    { en: "Sidi Akkacha", ar: "سيدي عكاشة" },
    { en: "Sobha", ar: "الصبحة" },
    { en: "Tadjena", ar: "تاجنة" },
    { en: "Talassa", ar: "تلعصة" },
    { en: "Taougrit", ar: "تاوقريت" },
    { en: "Tenes", ar: "تنس" },
    { en: "Zeboudja", ar: "الزبوجة" },
  ],
  "03": [
    { en: "Aflou", ar: "أفلو" },
    { en: "Ain Madhi", ar: "عين ماضي" },
    { en: "Ain Sidi Ali", ar: "عين سيدي علي" },
    { en: "Benacer Benchohra", ar: "بن ناصر بن شهرة" },
    { en: "Brida", ar: "بريدة" },
    { en: "El Assafia", ar: "العسافية" },
    { en: "El Beidha", ar: "البيضاء" },
    { en: "El Ghicha", ar: "الغيشة" },
    { en: "El Haouaita", ar: "الحويطة" },
    { en: "Gueltat Sidi Saad", ar: "قلتة سيدي سعد" },
    { en: "Hadj Mechri", ar: "الحاج مشري" },
    { en: "Hassi Delaa", ar: "حاسي الدلاعة" },
    { en: "Hassi R'mel", ar: "حاسي الرمل" },
    { en: "Kheneg", ar: "الخنق" },
    { en: "Ksar El Hirane", ar: "قصر الحيران" },
    { en: "Laghouat", ar: "الأغواط" },
    { en: "Oued M'zi", ar: "وادي مزي" },
    { en: "Oued Morra", ar: "وادي مرة" },
    { en: "Sebgag", ar: "سبقاق" },
    { en: "Sidi Bouzid", ar: "سيدي بوزيد" },
    { en: "Sidi Makhlouf", ar: "سيدي مخلوف" },
    { en: "Tadjemout", ar: "تاجموت" },
    { en: "Tadjrouna", ar: "تاجرونة" },
    { en: "Taouiala", ar: "تاويالة" },
  ],
  "04": [
    { en: "Ain Babouche", ar: "عين ببوش" },
    { en: "Ain Beida", ar: "عين البيضاء" },
    { en: "Ain Diss", ar: "عين الديس" },
    { en: "Ain Fekroun", ar: "عين فكرون" },
    { en: "Ain Kercha", ar: "عين كرشة" },
    { en: "Ain M'lila", ar: "عين مليلة" },
    { en: "Ain Zitoun", ar: "عين الزيتون" },
    { en: "Behir Chergui", ar: "بحير الشرقي" },
    { en: "Berriche", ar: "بريش" },
    { en: "Bir Chouhada", ar: "بئر الشهداء" },
    { en: "Dhalaa", ar: "الضلعة" },
    { en: "El Amiria", ar: "العامرية" },
    { en: "El Belala", ar: "البلالة" },
    { en: "El Djazia", ar: "الجازية" },
    { en: "El Fedjoudj Boughrara Sa", ar: "الفجوج بوغرارة سعودي" },
    { en: "El Harmilia", ar: "الحرملية" },
    { en: "Fkirina", ar: "فكيرينة" },
    { en: "Hanchir Toumghani", ar: "هنشير تومغني" },
    { en: "Ksar Sbahi", ar: "قصر الصباحي" },
    { en: "Meskiana", ar: "مسكيانة" },
    { en: "Oued Nini", ar: "وادي نيني" },
    { en: "Ouled Gacem", ar: "أولاد قاسم" },
    { en: "Ouled Hamla", ar: "أولاد حملة" },
    { en: "Ouled Zouai", ar: "أولاد زواي" },
    { en: "Oum El Bouaghi", ar: "أم البواقي" },
    { en: "Rahia", ar: "الرحية" },
    { en: "Sigus", ar: "سيقوس" },
    { en: "Souk Naamane", ar: "سوق نعمان" },
    { en: "Zorg", ar: "الزرق" },
  ],
  "05": [
    { en: "Ain Djasser", ar: "عين جاسر" },
    { en: "Ain Touta", ar: "عين التوتة" },
    { en: "Ain Yagout", ar: "عين ياقوت" },
    { en: "Arris", ar: "أريس" },
    { en: "Azil Abedelkader", ar: "عزيل عبد القادر" },
    { en: "Barika", ar: "بريكة" },
    { en: "Batna", ar: "باتنة" },
    { en: "Beni Foudhala El Hakania", ar: "بني فضالة الحقانية" },
    { en: "Bitam", ar: "بيطام" },
    { en: "Boulhilat", ar: "بولهيلات" },
    { en: "Boumagueur", ar: "بومقر" },
    { en: "Boumia", ar: "بومية" },
    { en: "Bouzina", ar: "بوزينة" },
    { en: "Chemora", ar: "الشمرة" },
    { en: "Chir", ar: "شير" },
    { en: "Djerma", ar: "جرمة" },
    { en: "Djezzar", ar: "الجزار" },
    { en: "El Hassi", ar: "الحاسي" },
    { en: "El Madher", ar: "المعذر" },
    { en: "Fesdis", ar: "فسديس" },
    { en: "Foum Toub", ar: "فم الطوب" },
    { en: "Ghassira", ar: "غسيرة" },
    { en: "Gosbat", ar: "القصبات" },
    { en: "Guigba", ar: "القيقبة" },
    { en: "Hidoussa", ar: "حيدوسة" },
    { en: "Ichemoul", ar: "إشمول" },
    { en: "Inoughissen", ar: "إينوغيسن" },
    { en: "Kimmel", ar: "كيمل" },
    { en: "Ksar Bellezma", ar: "قصر بلزمة" },
    { en: "Larbaa", ar: "لارباع" },
    { en: "Lazrou", ar: "لازرو" },
    { en: "Lemcene", ar: "لمسان" },
    { en: "M Doukal", ar: "إمدوكل" },
    { en: "Maafa", ar: "معافة" },
    { en: "Menaa", ar: "منعة" },
    { en: "Merouana", ar: "مروانة" },
    { en: "N Gaous", ar: "نقاوس" },
    { en: "Oued Chaaba", ar: "وادي الشعبة" },
    { en: "Oued El Ma", ar: "وادي الماء" },
    { en: "Oued Taga", ar: "وادي الطاقة" },
    { en: "Ouled Ammar", ar: "أولاد عمار" },
    { en: "Ouled Aouf", ar: "أولاد عوف" },
    { en: "Ouled Fadel", ar: "أولاد فاضل" },
    { en: "Ouled Sellem", ar: "أولاد سلام" },
    { en: "Ouled Si Slimane", ar: "أولاد سي سليمان" },
    { en: "Ouyoun El Assafir", ar: "عيون العصافير" },
    { en: "Rahbat", ar: "الرحبات" },
    { en: "Ras El Aioun", ar: "رأس العيون" },
    { en: "Sefiane", ar: "سفيان" },
    { en: "Seggana", ar: "سقانة" },
    { en: "Seriana", ar: "سريانة" },
    { en: "T Kout", ar: "تكوت" },
    { en: "Talkhamt", ar: "تالخمت" },
    { en: "Taxlent", ar: "تاكسلانت" },
    { en: "Tazoult", ar: "تازولت" },
    { en: "Teniet El Abed", ar: "ثنية العابد" },
    { en: "Tighanimine", ar: "تيغانمين" },
    { en: "Tigharghar", ar: "تغرغار" },
    { en: "Tilatou", ar: "تيلاطو" },
    { en: "Timgad", ar: "تيمقاد" },
    { en: "Zanet El Beida", ar: "زانة البيضاء" },
  ],
  "06": [
    { en: "Adekar", ar: "أدكار" },
    { en: "Ait R'zine", ar: "أيت رزين" },
    { en: "Ait-Smail", ar: "أيت إسماعيل" },
    { en: "Akbou", ar: "أقبو" },
    { en: "Akfadou", ar: "أكفادو" },
    { en: "Amalou", ar: "أمالو" },
    { en: "Amizour", ar: "أميزور" },
    { en: "Aokas", ar: "أوقاس" },
    { en: "Barbacha", ar: "برباشة" },
    { en: "Bejaia", ar: "بجاية" },
    { en: "Beni Djellil", ar: "بني جليل" },
    { en: "Beni K'sila", ar: "بني كسيلة" },
    { en: "Beni-Mallikeche", ar: "بني مليكش" },
    { en: "Benimaouche", ar: "بني معوش" },
    { en: "Boudjellil", ar: "بو جليل" },
    { en: "Bouhamza", ar: "بوحمزة" },
    { en: "Boukhelifa", ar: "بوخليفة" },
    { en: "Chellata", ar: "شلاطة" },
    { en: "Chemini", ar: "شميني" },
    { en: "Darguina", ar: "درقينة" },
    { en: "Dra El Caid", ar: "ذراع القايد" },
    { en: "El Kseur", ar: "القصر" },
    { en: "Fenaia Il Maten", ar: "فناية الماثن" },
    { en: "Feraoun", ar: "فرعون" },
    { en: "Ighil-Ali", ar: "إغيل علي" },
    { en: "Ighram", ar: "اغرم" },
    { en: "Kendira", ar: "كنديرة" },
    { en: "Kherrata", ar: "خراطة" },
    { en: "Leflaye", ar: "الفلاي" },
    { en: "M'cisna", ar: "مسيسنة" },
    { en: "Melbou", ar: "مالبو" },
    { en: "Oued Ghir", ar: "وادي غير" },
    { en: "Ouzellaguen", ar: "أوزلاقن" },
    { en: "Seddouk", ar: "صدوق" },
    { en: "Sidi Ayad", ar: "سيدي عياد" },
    { en: "Sidi-Aich", ar: "سيدي عيش" },
    { en: "Smaoun", ar: "سمعون" },
    { en: "Souk El Tenine", ar: "سوق لإثنين" },
    { en: "Souk Oufella", ar: "سوق اوفلا" },
    { en: "Tala Hamza", ar: "تالة حمزة" },
    { en: "Tamokra", ar: "تامقرة" },
    { en: "Tamridjet", ar: "تامريجت" },
    { en: "Taourit Ighil", ar: "تاوريرت إغيل" },
    { en: "Taskriout", ar: "تاسكريوت" },
    { en: "Tazmalt", ar: "تازمالت" },
    { en: "Tibane", ar: "طيبان" },
    { en: "Tichy", ar: "تيشي" },
    { en: "Tifra", ar: "تيفرة" },
    { en: "Timezrit", ar: "تيمزريت" },
    { en: "Tinebdar", ar: "تينبدار" },
    { en: "Tizi-N'berber", ar: "تيزي نبربر" },
    { en: "Toudja", ar: "توجة" },
  ],
  "07": [
    { en: "Ain Naga", ar: "عين الناقة" },
    { en: "Ain Zaatout", ar: "عين زعطوط" },
    { en: "Biskra", ar: "بسكرة" },
    { en: "Bordj Ben Azzouz", ar: "برج بن عزوز" },
    { en: "Bouchakroun", ar: "بوشقرون" },
    { en: "Branis", ar: "برانيس" },
    { en: "Chetma", ar: "شتمة" },
    { en: "Djemorah", ar: "جمورة" },
    { en: "El Feidh", ar: "الفيض" },
    { en: "El Ghrous", ar: "الغروس" },
    { en: "El Hadjab", ar: "الحاجب" },
    { en: "El Haouch", ar: "الحوش" },
    { en: "El Kantara", ar: "القنطرة" },
    { en: "El Outaya", ar: "الوطاية" },
    { en: "Foughala", ar: "فوغالة" },
    { en: "Khenguet Sidi Nadji", ar: "خنقة سيدي ناجي" },
    { en: "Lichana", ar: "ليشانة" },
    { en: "Lioua", ar: "ليوة" },
    { en: "M'chouneche", ar: "مشونش" },
    { en: "M'lili", ar: "مليلي" },
    { en: "Mekhadma", ar: "مخادمة" },
    { en: "Meziraa", ar: "المزيرعة" },
    { en: "Oumache", ar: "أوماش" },
    { en: "Ourlal", ar: "أورلال" },
    { en: "Sidi Okba", ar: "سيدي عقبة" },
    { en: "Tolga", ar: "طولقة" },
    { en: "Zeribet El Oued", ar: "زريبة الوادي" },
  ],
  "08": [
    { en: "Abadla", ar: "العبادلة" },
    { en: "Bechar", ar: "بشار" },
    { en: "Beni-Ounif", ar: "بني ونيف" },
    { en: "Boukais", ar: "بوكايس" },
    { en: "Erg-Ferradj", ar: "عرق فراج" },
    { en: "Kenadsa", ar: "القنادسة" },
    { en: "Lahmar", ar: "لحمر" },
    { en: "Machraa-Houari-Boumediene", ar: "مشرع هواري بومدين" },
    { en: "Meridja", ar: "المريجة" },
    { en: "Mogheul", ar: "موغل" },
    { en: "Tabelbala", ar: "تبلبالة" },
    { en: "Taghit", ar: "تاغيت" },
  ],
  "09": [
    { en: "Ain Romana", ar: "عين الرمانة" },
    { en: "Beni Mered", ar: "بني مراد" },
    { en: "Beni-Tamou", ar: "بني تامو" },
    { en: "Benkhelil", ar: "بن خليل" },
    { en: "Blida", ar: "البليدة" },
    { en: "Bouarfa", ar: "بوعرفة" },
    { en: "Boufarik", ar: "بوفاريك" },
    { en: "Bougara", ar: "بوقرة" },
    { en: "Bouinan", ar: "بوعينان" },
    { en: "Chebli", ar: "الشبلي" },
    { en: "Chiffa", ar: "الشفة" },
    { en: "Chrea", ar: "الشريعة" },
    { en: "Djebabra", ar: "جبابرة" },
    { en: "El-Affroun", ar: "العفرون" },
    { en: "Guerrouaou", ar: "قرواو" },
    { en: "Hammam Elouane", ar: "حمام ملوان" },
    { en: "Larbaa", ar: "الأربعاء" },
    { en: "Meftah", ar: "مفتاح" },
    { en: "Mouzaia", ar: "موزاية" },
    { en: "Oued  Djer", ar: "وادي جر" },
    { en: "Oued El Alleug", ar: "وادي العلايق" },
    { en: "Ouled Slama", ar: "اولاد سلامة" },
    { en: "Ouled Yaich", ar: "أولاد يعيش" },
    { en: "Souhane", ar: "صوحان" },
    { en: "Soumaa", ar: "الصومعة" },
  ],
  "10": [
    { en: "Aghbalou", ar: "أغبالو" },
    { en: "Ahl El Ksar", ar: "أهل القصر" },
    { en: "Ain El Hadjar", ar: "عين الحجر" },
    { en: "Ain Laloui", ar: "عين العلوي" },
    { en: "Ain Turk", ar: "عين الترك" },
    { en: "Ain-Bessem", ar: "عين بسام" },
    { en: "Ait Laaziz", ar: "أيت لعزيز" },
    { en: "Aomar", ar: "أعمر" },
    { en: "Ath Mansour", ar: "آث  منصور" },
    { en: "Bechloul", ar: "بشلول" },
    { en: "Bir Ghbalou", ar: "بئر غبالو" },
    { en: "Bordj Okhriss", ar: "برج أوخريص" },
    { en: "Bouderbala", ar: "بودربالة" },
    { en: "Bouira", ar: "البويرة" },
    { en: "Boukram", ar: "بوكرم" },
    { en: "Chorfa", ar: "شرفة" },
    { en: "Dechmia", ar: "الدشمية" },
    { en: "Dirah", ar: "ديرة" },
    { en: "Djebahia", ar: "جباحية" },
    { en: "El Adjiba", ar: "العجيبة" },
    { en: "El Asnam", ar: "الأسنام" },
    { en: "El Hachimia", ar: "الهاشمية" },
    { en: "El Khabouzia", ar: "الخبوزية" },
    { en: "El-Hakimia", ar: "الحاكمية" },
    { en: "El-Mokrani", ar: "المقراني" },
    { en: "Guerrouma", ar: "قرومة" },
    { en: "Hadjera Zerga", ar: "الحجرة الزرقاء" },
    { en: "Haizer", ar: "حيزر" },
    { en: "Hanif", ar: "حنيف" },
    { en: "Kadiria", ar: "قادرية" },
    { en: "Lakhdaria", ar: "الأخضرية" },
    { en: "M Chedallah", ar: "أمشدالة" },
    { en: "Maala", ar: "معلة" },
    { en: "Maamora", ar: "المعمورة" },
    { en: "Mezdour", ar: "مزدور" },
    { en: "Oued El Berdi", ar: "وادي البردي" },
    { en: "Ouled Rached", ar: "أولاد راشد" },
    { en: "Raouraoua", ar: "روراوة" },
    { en: "Ridane", ar: "ريدان" },
    { en: "Saharidj", ar: "سحاريج" },
    { en: "Souk El Khemis", ar: "سوق الخميس" },
    { en: "Sour El Ghozlane", ar: "سور الغزلان" },
    { en: "Taghzout", ar: "تاغزوت" },
    { en: "Taguedite", ar: "تاقديت" },
    { en: "Z'barbar (El Isseri )", ar: "زبربر" },
  ],
  "11": [
    { en: "Abelsa", ar: "ابلسة" },
    { en: "Ain Amguel", ar: "عين امقل" },
    { en: "Idles", ar: "أدلس" },
    { en: "Tamanrasset", ar: "تمنراست" },
    { en: "Tazrouk", ar: "تاظروك" },
  ],
  "12": [
    { en: "Ain Zerga", ar: "عين الزرقاء" },
    { en: "Bedjene", ar: "بجن" },
    { en: "Bekkaria", ar: "بكارية" },
    { en: "Bir Dheheb", ar: "بئر الذهب" },
    { en: "Bir Mokkadem", ar: "بئر مقدم" },
    { en: "Bir-El-Ater", ar: "بئر العاتر" },
    { en: "Boukhadra", ar: "بوخضرة" },
    { en: "Boulhaf Dyr", ar: "بولحاف الدير" },
    { en: "Cheria", ar: "الشريعة" },
    { en: "El Kouif", ar: "الكويف" },
    { en: "El Malabiod", ar: "الماء الابيض" },
    { en: "El Meridj", ar: "المريج" },
    { en: "El Mezeraa", ar: "المزرعة" },
    { en: "El Ogla", ar: "العقلة" },
    { en: "El Ogla El Malha", ar: "العقلة المالحة" },
    { en: "El-Aouinet", ar: "العوينات" },
    { en: "El-Houidjbet", ar: "الحويجبات" },
    { en: "Ferkane", ar: "فركان" },
    { en: "Guorriguer", ar: "قريقر" },
    { en: "Hammamet", ar: "الحمامات" },
    { en: "Morsott", ar: "مرسط" },
    { en: "Negrine", ar: "نقرين" },
    { en: "Ouenza", ar: "الونزة" },
    { en: "Oum Ali", ar: "أم علي" },
    { en: "Saf Saf El Ouesra", ar: "صفصاف الوسرى" },
    { en: "Stah Guentis", ar: "سطح قنطيس" },
    { en: "Tebessa", ar: "تبسة" },
    { en: "Telidjen", ar: "ثليجان" },
  ],
  "13": [
    { en: "Ain Fetah", ar: "عين فتاح" },
    { en: "Ain Fezza", ar: "عين فزة" },
    { en: "Ain Ghoraba", ar: "عين غرابة" },
    { en: "Ain Kebira", ar: "عين الكبيرة" },
    { en: "Ain Nehala", ar: "عين النحالة" },
    { en: "Ain Tellout", ar: "عين تالوت" },
    { en: "Ain Youcef", ar: "عين يوسف" },
    { en: "Amieur", ar: "عمير" },
    { en: "Azail", ar: "العزايل" },
    { en: "Bab El Assa", ar: "باب العسة" },
    { en: "Beni Bahdel", ar: "بني بهدل" },
    { en: "Beni Boussaid", ar: "بني بوسعيد" },
    { en: "Beni Khellad", ar: "بني خلاد" },
    { en: "Beni Mester", ar: "بني مستر" },
    { en: "Beni Ouarsous", ar: "بني وارسوس" },
    { en: "Beni Smiel", ar: "بني صميل" },
    { en: "Beni Snous", ar: "بني سنوس" },
    { en: "Bensekrane", ar: "بن سكران" },
    { en: "Bouhlou", ar: "بوحلو" },
    { en: "Bouihi", ar: "البويهي" },
    { en: "Chetouane", ar: "شتوان" },
    { en: "Dar Yaghmoracen", ar: "دار يغمراسن" },
    { en: "Djebala", ar: "جبالة" },
    { en: "El Aricha", ar: "العريشة" },
    { en: "El Fehoul", ar: "الفحول" },
    { en: "El Gor", ar: "القور" },
    { en: "Fellaoucene", ar: "فلاوسن" },
    { en: "Ghazaouet", ar: "الغزوات" },
    { en: "Hammam Boughrara", ar: "حمام بوغرارة" },
    { en: "Hennaya", ar: "الحناية" },
    { en: "Honnaine", ar: "هنين" },
    { en: "M'sirda Fouaga", ar: "مسيردة الفواقة" },
    { en: "Maghnia", ar: "مغنية" },
    { en: "Mansourah", ar: "منصورة" },
    { en: "Marsa Ben M'hidi", ar: "مرسى بن مهيدي" },
    { en: "Nedroma", ar: "ندرومة" },
    { en: "Oued Lakhdar", ar: "وادي الخضر" },
    { en: "Ouled Mimoun", ar: "أولاد ميمون" },
    { en: "Ouled Riyah", ar: "أولاد رياح" },
    { en: "Remchi", ar: "الرمشي" },
    { en: "Sabra", ar: "صبرة" },
    { en: "Sebbaa Chioukh", ar: "سبعة شيوخ" },
    { en: "Sebdou", ar: "سبدو" },
    { en: "Sidi Abdelli", ar: "سيدي العبدلي" },
    { en: "Sidi Djillali", ar: "سيدي الجيلالي" },
    { en: "Sidi Medjahed", ar: "سيدي مجاهد" },
    { en: "Souahlia", ar: "السواحلية" },
    { en: "Souani", ar: "السواني" },
    { en: "Souk Tleta", ar: "سوق الثلاثاء" },
    { en: "Terny Beni Hediel", ar: "تيرني بني هديل" },
    { en: "Tianet", ar: "تيانت" },
    { en: "Tlemcen", ar: "تلمسان" },
    { en: "Zenata", ar: "زناتة" },
  ],
  "14": [
    { en: "Ain Bouchekif", ar: "عين بوشقيف" },
    { en: "Ain Deheb", ar: "عين الذهب" },
    { en: "Ain Dzarit", ar: "عين دزاريت" },
    { en: "Ain El Hadid", ar: "عين الحديد" },
    { en: "Ain Kermes", ar: "عين كرمس" },
    { en: "Bougara", ar: "بوقرة" },
    { en: "Chehaima", ar: "شحيمة" },
    { en: "Dahmouni", ar: "دحموني" },
    { en: "Djebilet Rosfa", ar: "جبيلات الرصفاء" },
    { en: "Djillali Ben Amar", ar: "جيلالي بن عمار" },
    { en: "Faidja", ar: "الفايجة" },
    { en: "Frenda", ar: "فرندة" },
    { en: "Guertoufa", ar: "قرطوفة" },
    { en: "Hamadia", ar: "حمادية" },
    { en: "Ksar Chellala", ar: "قصر الشلالة" },
    { en: "Madna", ar: "مادنة" },
    { en: "Mahdia", ar: "مهدية" },
    { en: "Mechraa Safa", ar: "مشرع الصفا" },
    { en: "Medrissa", ar: "مدريسة" },
    { en: "Medroussa", ar: "مدروسة" },
    { en: "Meghila", ar: "مغيلة" },
    { en: "Mellakou", ar: "ملاكو" },
    { en: "Nadorah", ar: "الناظورة" },
    { en: "Naima", ar: "النعيمة" },
    { en: "Oued Lilli", ar: "وادي ليلي" },
    { en: "Rahouia", ar: "الرحوية" },
    { en: "Rechaiga", ar: "الرشايقة" },
    { en: "Sebaine", ar: "السبعين" },
    { en: "Sebt", ar: "السبت" },
    { en: "Serghine", ar: "سرغين" },
    { en: "Si Abdelghani", ar: "سي عبد الغني" },
    { en: "Sidi Abderrahmane", ar: "سيدي عبد الرحمن" },
    { en: "Sidi Ali Mellal", ar: "سيدي علي ملال" },
    { en: "Sidi Bakhti", ar: "سيدي بختي" },
    { en: "Sidi Hosni", ar: "سيدي حسني" },
    { en: "Sougueur", ar: "السوقر" },
    { en: "Tagdempt", ar: "تاقدمت" },
    { en: "Takhemaret", ar: "تخمرت" },
    { en: "Tiaret", ar: "تيارت" },
    { en: "Tidda", ar: "تيدة" },
    { en: "Tousnina", ar: "توسنينة" },
    { en: "Zmalet El Emir Abdelkade", ar: "زمالة  الأمير عبد القادر" },
  ],
  "15": [
    { en: "Abi-Youcef", ar: "أبي يوسف" },
    { en: "Aghribs", ar: "أغريب" },
    { en: "Agouni-Gueghrane", ar: "أقني قغران" },
    { en: "Ain-El-Hammam", ar: "عين الحمام" },
    { en: "Ain-Zaouia", ar: "عين الزاوية" },
    { en: "Ait Aggouacha", ar: "أيت عقـواشة" },
    { en: "Ait Bouaddou", ar: "أيت بــوادو" },
    { en: "Ait Boumahdi", ar: "أيت بومهدي" },
    { en: "Ait Khellili", ar: "أيت خليلي" },
    { en: "Ait Yahia Moussa", ar: "أيت يحي موسى" },
    { en: "Ait-Aissa-Mimoun", ar: "أيت عيسى ميمون" },
    { en: "Ait-Chafaa", ar: "أيت شافع" },
    { en: "Ait-Mahmoud", ar: "أيت محمود" },
    { en: "Ait-Oumalou", ar: "أيت  أومالو" },
    { en: "Ait-Toudert", ar: "أيت تودرت" },
    { en: "Ait-Yahia", ar: "أيت يحيى" },
    { en: "Akbil", ar: "اقبيل" },
    { en: "Akerrou", ar: "أقرو" },
    { en: "Assi-Youcef", ar: "أسي يوسف" },
    { en: "Azazga", ar: "عزازقة" },
    { en: "Azeffoun", ar: "أزفون" },
    { en: "Beni Zmenzer", ar: "بنــــي زمنزار" },
    { en: "Beni-Aissi", ar: "بني عيسي" },
    { en: "Beni-Douala", ar: "بني دوالة" },
    { en: "Beni-Yenni", ar: "بني يني" },
    { en: "Beni-Zikki", ar: "بني زيكــي" },
    { en: "Boghni", ar: "بوغني" },
    { en: "Boudjima", ar: "بوجيمة" },
    { en: "Bounouh", ar: "بونوح" },
    { en: "Bouzeguene", ar: "بوزقــن" },
    { en: "Draa-Ben-Khedda", ar: "ذراع بن خدة" },
    { en: "Draa-El-Mizan", ar: "ذراع الميزان" },
    { en: "Freha", ar: "فريحة" },
    { en: "Frikat", ar: "فريقات" },
    { en: "Iboudrarene", ar: "إبودرارن" },
    { en: "Idjeur", ar: "إيجــار" },
    { en: "Iferhounene", ar: "إفــرحــونان" },
    { en: "Ifigha", ar: "إيفيغاء" },
    { en: "Iflissen", ar: "إفليـــسن" },
    { en: "Illilten", ar: "إيلـيــلتـن" },
    { en: "Illoula Oumalou", ar: "إيلولة أومـــالو" },
    { en: "Imsouhal", ar: "إمســوحال" },
    { en: "Irdjen", ar: "إيرجـــن" },
    { en: "Larbaa Nath Irathen", ar: "الأربعــاء ناث إيراثن" },
    { en: "M'kira", ar: "مكيرة" },
    { en: "Maatkas", ar: "معـــاتقة" },
    { en: "Makouda", ar: "ماكودة" },
    { en: "Mechtras", ar: "مشطراس" },
    { en: "Mekla", ar: "مقــلع" },
    { en: "Mizrana", ar: "ميزرانـــة" },
    { en: "Ouacif", ar: "واسيف" },
    { en: "Ouadhias", ar: "واضية" },
    { en: "Ouaguenoun", ar: "واقنون" },
    { en: "Sidi Namane", ar: "سيدي نعمان" },
    { en: "Souama", ar: "صوامـــع" },
    { en: "Souk-El-Tenine", ar: "سوق الإثنين" },
    { en: "Tadmait", ar: "تادمايت" },
    { en: "Tigzirt", ar: "تيقـزيرت" },
    { en: "Timizart", ar: "تيمـيزار" },
    { en: "Tirmitine", ar: "تيرمتين" },
    { en: "Tizi N'tleta", ar: "تيزي نثلاثة" },
    { en: "Tizi-Gheniff", ar: "تيزي غنيف" },
    { en: "Tizi-Ouzou", ar: "تيزي وزو" },
    { en: "Tizi-Rached", ar: "تيزي راشد" },
    { en: "Yakourene", ar: "إعــكورن" },
    { en: "Yatafene", ar: "يطــافن" },
    { en: "Zekri", ar: "زكري" },
  ],
  "16": [
    { en: "Ain Benian", ar: "عين بنيان" },
    { en: "Ain Taya", ar: "عين طاية" },
    { en: "Alger Centre", ar: "الجزائر الوسطى" },
    { en: "Bab El Oued", ar: "باب الوادي" },
    { en: "Bab Ezzouar", ar: "باب الزوار" },
    { en: "Baba Hassen", ar: "بابا حسن" },
    { en: "Bachedjerah", ar: "باش جراح" },
    { en: "Baraki", ar: "براقي" },
    { en: "Ben Aknoun", ar: "ابن عكنون" },
    { en: "Beni Messous", ar: "بني مسوس" },
    { en: "Bir Mourad Rais", ar: "بئر مراد رايس" },
    { en: "Bir Touta", ar: "بئر توتة" },
    { en: "Birkhadem", ar: "بئر خادم" },
    { en: "Bologhine Ibnou Ziri", ar: "بولوغين بن زيري" },
    { en: "Bordj El Bahri", ar: "برج البحري" },
    { en: "Bordj El Kiffan", ar: "برج الكيفان" },
    { en: "Bourouba", ar: "بوروبة" },
    { en: "Bouzareah", ar: "بوزريعة" },
    { en: "Casbah", ar: "القصبة" },
    { en: "Cheraga", ar: "الشراقة" },
    { en: "Dar El Beida", ar: "الدار البيضاء" },
    { en: "Dely Ibrahim", ar: "دالي ابراهيم" },
    { en: "Djasr Kasentina", ar: "جسر قسنطينة" },
    { en: "Douira", ar: "الدويرة" },
    { en: "Draria", ar: "الدرارية" },
    { en: "El Achour", ar: "العاشور" },
    { en: "El Biar", ar: "الابيار" },
    { en: "El Harrach", ar: "الحراش" },
    { en: "El Madania", ar: "المدنية" },
    { en: "El Magharia", ar: "المغارية" },
    { en: "El Marsa", ar: "المرسى" },
    { en: "El Mouradia", ar: "المرادية" },
    { en: "Hammamet", ar: "الحمامات" },
    { en: "Herraoua", ar: "هراوة" },
    { en: "Hussein Dey", ar: "حسين داي" },
    { en: "Hydra", ar: "حيدرة" },
    { en: "Khraissia", ar: "الخرايسية" },
    { en: "Kouba", ar: "القبة" },
    { en: "Les Eucalyptus", ar: "الكاليتوس" },
    { en: "Maalma", ar: "المعالمة" },
    { en: "Mohamed Belouzdad", ar: "محمد بلوزداد" },
    { en: "Mohammadia", ar: "المحمدية" },
    { en: "Oued Koriche", ar: "وادي قريش" },
    { en: "Oued Smar", ar: "وادي السمار" },
    { en: "Ouled Chebel", ar: "اولاد شبل" },
    { en: "Ouled Fayet", ar: "اولاد فايت" },
    { en: "Rahmania", ar: "الرحمانية" },
    { en: "Rais Hamidou", ar: "الرايس حميدو" },
    { en: "Reghaia", ar: "رغاية" },
    { en: "Rouiba", ar: "الرويبة" },
    { en: "Sehaoula", ar: "السحاولة" },
    { en: "Sidi M'hamed", ar: "سيدي امحمد" },
    { en: "Sidi Moussa", ar: "سيدي موسى" },
    { en: "Souidania", ar: "سويدانية" },
    { en: "Staoueli", ar: "سطاوالي" },
    { en: "Tessala El Merdja", ar: "تسالة المرجة" },
    { en: "Zeralda", ar: "زرالدة" },
  ],
  "17": [
    { en: "Ain Chouhada", ar: "عين الشهداء" },
    { en: "Ain El Ibel", ar: "عين الإبل" },
    { en: "Ain Fekka", ar: "عين فقه" },
    { en: "Ain Maabed", ar: "عين معبد" },
    { en: "Ain Oussera", ar: "عين وسارة" },
    { en: "Amourah", ar: "عمورة" },
    { en: "Benhar", ar: "بنهار" },
    { en: "Benyagoub", ar: "بن يعقوب" },
    { en: "Birine", ar: "بيرين" },
    { en: "Bouira Lahdab", ar: "بويرة الأحداب" },
    { en: "Charef", ar: "الشارف" },
    { en: "Dar Chioukh", ar: "دار الشيوخ" },
    { en: "Deldoul", ar: "دلدول" },
    { en: "Djelfa", ar: "الجلفة" },
    { en: "Douis", ar: "دويس" },
    { en: "El Guedid", ar: "القديد" },
    { en: "El Idrissia", ar: "الادريسية" },
    { en: "El Khemis", ar: "الخميس" },
    { en: "Faidh El Botma", ar: "فيض البطمة" },
    { en: "Guernini", ar: "قرنيني" },
    { en: "Guettara", ar: "قطارة" },
    { en: "Had Sahary", ar: "حد الصحاري" },
    { en: "Hassi Bahbah", ar: "حاسي بحبح" },
    { en: "Hassi El Euch", ar: "حاسي العش" },
    { en: "Hassi Fedoul", ar: "حاسي فدول" },
    { en: "M'liliha", ar: "مليليحة" },
    { en: "Messaad", ar: "مسعد" },
    { en: "Moudjebara", ar: "مجبارة" },
    { en: "Oum Laadham", ar: "أم العظام" },
    { en: "Sed Rahal", ar: "سد الرحال" },
    { en: "Selmana", ar: "سلمانة" },
    { en: "Sidi Baizid", ar: "سيدي بايزيد" },
    { en: "Sidi Laadjel", ar: "سيدي لعجال" },
    { en: "Taadmit", ar: "تعظميت" },
    { en: "Zaafrane", ar: "زعفران" },
    { en: "Zaccar", ar: "زكار" },
  ],
  "18": [
    { en: "Bordj T'har", ar: "برج الطهر" },
    { en: "Boudria Beniyadjis", ar: "بودريعة بني  ياجيس" },
    { en: "Bouraoui Belhadef", ar: "بوراوي بلهادف" },
    { en: "Boussif Ouled Askeur", ar: "بوسيف أولاد عسكر" },
    { en: "Chahna", ar: "الشحنة" },
    { en: "Chekfa", ar: "الشقفة" },
    { en: "Djemaa Beni Habibi", ar: "الجمعة بني حبيبي" },
    { en: "Djimla", ar: "جيملة" },
    { en: "El Ancer", ar: "العنصر" },
    { en: "El Aouana", ar: "العوانة" },
    { en: "El Kennar Nouchfi", ar: "القنار نشفي" },
    { en: "El Milia", ar: "الميلية" },
    { en: "Emir Abdelkader", ar: "الامير عبد القادر" },
    { en: "Erraguene Souissi", ar: "أراقن سويسي" },
    { en: "Ghebala", ar: "غبالة" },
    { en: "Jijel", ar: "جيجل" },
    { en: "Kaous", ar: "قاوس" },
    { en: "Khiri Oued Adjoul", ar: "خيري واد عجول" },
    { en: "Oudjana", ar: "وجانة" },
    { en: "Ouled Rabah", ar: "أولاد رابح" },
    { en: "Ouled Yahia Khadrouch", ar: "أولاد يحيى خدروش" },
    { en: "Selma Benziada", ar: "سلمى بن زيادة" },
    { en: "Settara", ar: "السطارة" },
    { en: "Sidi Abdelaziz", ar: "سيدي عبد العزيز" },
    { en: "Sidi Marouf", ar: "سيدي معروف" },
    { en: "Taher", ar: "الطاهير" },
    { en: "Texenna", ar: "تاكسنة" },
    { en: "Ziama Mansouriah", ar: "زيامة منصورية" },
  ],
  "19": [
    { en: "Ain Abessa", ar: "عين عباسة" },
    { en: "Ain Arnat", ar: "عين أرنات" },
    { en: "Ain Azel", ar: "عين أزال" },
    { en: "Ain El Kebira", ar: "عين الكبيرة" },
    { en: "Ain Lahdjar", ar: "عين الحجر" },
    { en: "Ain Oulmene", ar: "عين ولمان" },
    { en: "Ain-Legradj", ar: "عين لقراج" },
    { en: "Ain-Roua", ar: "عين الروى" },
    { en: "Ain-Sebt", ar: "عين السبت" },
    { en: "Ait Naoual Mezada", ar: "أيت نوال مزادة" },
    { en: "Ait-Tizi", ar: "ايت تيزي" },
    { en: "Amoucha", ar: "عموشة" },
    { en: "Babor", ar: "بابور" },
    { en: "Bazer-Sakra", ar: "بازر سكرة" },
    { en: "Beidha Bordj", ar: "بيضاء برج" },
    { en: "Bellaa", ar: "بلاعة" },
    { en: "Beni Chebana", ar: "بني شبانة" },
    { en: "Beni Fouda", ar: "بني فودة" },
    { en: "Beni Ourtilane", ar: "بني ورتيلان" },
    { en: "Beni Oussine", ar: "بني وسين" },
    { en: "Beni-Aziz", ar: "بني عزيز" },
    { en: "Beni-Mouhli", ar: "بني موحلي" },
    { en: "Bir Haddada", ar: "بئر حدادة" },
    { en: "Bir-El-Arch", ar: "بئر العرش" },
    { en: "Bouandas", ar: "بوعنداس" },
    { en: "Bougaa", ar: "بوقاعة" },
    { en: "Bousselam", ar: "بوسلام" },
    { en: "Boutaleb", ar: "بوطالب" },
    { en: "Dehamcha", ar: "الدهامشة" },
    { en: "Djemila", ar: "جميلة" },
    { en: "Draa-Kebila", ar: "ذراع قبيلة" },
    { en: "El Eulma", ar: "العلمة" },
    { en: "El Ouricia", ar: "أوريسيا" },
    { en: "El-Ouldja", ar: "الولجة" },
    { en: "Guellal", ar: "قلال" },
    { en: "Guelta Zerka", ar: "قلتة زرقاء" },
    { en: "Guenzet", ar: "قنزات" },
    { en: "Guidjel", ar: "قجال" },
    { en: "Hamam Soukhna", ar: "حمام السخنة" },
    { en: "Hamma", ar: "الحامة" },
    { en: "Hammam Guergour", ar: "حمام قرقور" },
    { en: "Harbil", ar: "حربيل" },
    { en: "Kasr El Abtal", ar: "قصر الابطال" },
    { en: "Maaouia", ar: "معاوية" },
    { en: "Maouaklane", ar: "ماوكلان" },
    { en: "Mezloug", ar: "مزلوق" },
    { en: "Oued El Bared", ar: "واد البارد" },
    { en: "Ouled Addouane", ar: "أولاد عدوان" },
    { en: "Ouled Sabor", ar: "أولاد صابر" },
    { en: "Ouled Si Ahmed", ar: "أولاد سي أحمد" },
    { en: "Ouled Tebben", ar: "أولاد تبان" },
    { en: "Rosfa", ar: "الرصفة" },
    { en: "Salah Bey", ar: "صالح باي" },
    { en: "Serdj-El-Ghoul", ar: "سرج الغول" },
    { en: "Setif", ar: "سطيف" },
    { en: "Tachouda", ar: "تاشودة" },
    { en: "Tala-Ifacene", ar: "تالة إيفاسن" },
    { en: "Taya", ar: "الطاية" },
    { en: "Tella", ar: "التلة" },
    { en: "Tizi N'bechar", ar: "تيزي نبشار" },
  ],
  "20": [
    { en: "Ain El Hadjar", ar: "عين الحجر" },
    { en: "Ain Sekhouna", ar: "عين السخونة" },
    { en: "Ain Soltane", ar: "عين السلطان" },
    { en: "Doui Thabet", ar: "دوي ثابت" },
    { en: "El Hassasna", ar: "الحساسنة" },
    { en: "Hounet", ar: "هونت" },
    { en: "Maamora", ar: "المعمورة" },
    { en: "Moulay Larbi", ar: "مولاي العربي" },
    { en: "Ouled Brahim", ar: "أولاد إبراهيم" },
    { en: "Ouled Khaled", ar: "أولاد خالد" },
    { en: "Saida", ar: "سعيدة" },
    { en: "Sidi Ahmed", ar: "سيدي احمد" },
    { en: "Sidi Amar", ar: "سيدي عمر" },
    { en: "Sidi Boubekeur", ar: "سيدي بوبكر" },
    { en: "Tircine", ar: "تيرسين" },
    { en: "Youb", ar: "يوب" },
  ],
  "21": [
    { en: "Ain Bouziane", ar: "عين بوزيان" },
    { en: "Ain Charchar", ar: "عين شرشار" },
    { en: "Ain Kechra", ar: "عين قشرة" },
    { en: "Ain Zouit", ar: "عين زويت" },
    { en: "Azzaba", ar: "عزابة" },
    { en: "Bekkouche Lakhdar", ar: "بكوش لخضر" },
    { en: "Ben Azzouz", ar: "بن عزوز" },
    { en: "Beni Bechir", ar: "بني بشير" },
    { en: "Beni Oulbane", ar: "بني ولبان" },
    { en: "Beni Zid", ar: "بني زيد" },
    { en: "Bin El Ouiden", ar: "بين الويدان" },
    { en: "Bouchetata", ar: "بوشطاطة" },
    { en: "Cheraia", ar: "الشرايع" },
    { en: "Collo", ar: "القل" },
    { en: "Djendel Saadi Mohamed", ar: "جندل سعدي محمد" },
    { en: "El Arrouch", ar: "الحروش" },
    { en: "El Ghedir", ar: "الغدير" },
    { en: "El Hadaiek", ar: "الحدائق" },
    { en: "El Marsa", ar: "المرسى" },
    { en: "Emjez Edchich", ar: "مجاز الدشيش" },
    { en: "Es Sebt", ar: "السبت" },
    { en: "Filfila", ar: "فلفلة" },
    { en: "Hammadi Krouma", ar: "حمادي كرومة" },
    { en: "Kanoua", ar: "قنواع" },
    { en: "Kerkara", ar: "الكركرة" },
    { en: "Khenag Maoune", ar: "خناق مايو" },
    { en: "Oued Zhour", ar: "وادي الزهور" },
    { en: "Ouldja Boulbalout", ar: "الولجة بولبلوط" },
    { en: "Ouled Attia", ar: "أولاد عطية" },
    { en: "Ouled Habbaba", ar: "أولاد حبابة" },
    { en: "Oum Toub", ar: "أم الطوب" },
    { en: "Ramdane Djamel", ar: "رمضان جمال" },
    { en: "Salah Bouchaour", ar: "صالح بو الشعور" },
    { en: "Sidi Mezghiche", ar: "سيدي مزغيش" },
    { en: "Skikda", ar: "سكيكدة" },
    { en: "Tamalous", ar: "تمالوس" },
    { en: "Zerdezas", ar: "زردازة" },
    { en: "Zitouna", ar: "الزيتونة" },
  ],
  "22": [
    { en: "Ain El Berd", ar: "عين البرد" },
    { en: "Ain Kada", ar: "عين قادة" },
    { en: "Ain Thrid", ar: "عين الثريد" },
    { en: "Ain Tindamine", ar: "عين تندمين" },
    { en: "Ain- Adden", ar: "عين أدن" },
    { en: "Amarnas", ar: "العمارنة" },
    { en: "Bedrabine El Mokrani", ar: "بضرابين المقراني" },
    { en: "Belarbi", ar: "بلعربي" },
    { en: "Ben Badis", ar: "بن باديس" },
    { en: "Benachiba Chelia", ar: "بن عشيبة شلية" },
    { en: "Bir El Hammam", ar: "بئر الحمام" },
    { en: "Boudjebaa El Bordj", ar: "بوجبهة البرج" },
    { en: "Boukhanefis", ar: "بوخنفيس" },
    { en: "Chetouane Belaila", ar: "شيطوان البلايلة" },
    { en: "Dhaya", ar: "الضاية" },
    { en: "El Hacaiba", ar: "الحصيبة" },
    { en: "Hassi Dahou", ar: "حاسي دحو" },
    { en: "Hassi Zahana", ar: "حاسي زهانة" },
    { en: "Lamtar", ar: "لمطار" },
    { en: "M'cid", ar: "مسيد" },
    { en: "Makedra", ar: "مكدرة" },
    { en: "Marhoum", ar: "مرحوم" },
    { en: "Merine", ar: "مرين" },
    { en: "Mezaourou", ar: "مزاورو" },
    { en: "Mostefa  Ben Brahim", ar: "مصطفى بن ابراهيم" },
    { en: "Moulay Slissen", ar: "مولاي سليسن" },
    { en: "Oued Sebaa", ar: "وادي السبع" },
    { en: "Oued Sefioun", ar: "وادي سفيون" },
    { en: "Oued Taourira", ar: "وادي تاوريرة" },
    { en: "Ras El Ma", ar: "راس الماء" },
    { en: "Redjem Demouche", ar: "رجم دموش" },
    { en: "Sehala Thaoura", ar: "السهالة الثورة" },
    { en: "Sfisef", ar: "سفيزف" },
    { en: "Sidi Ali Benyoub", ar: "سيدي علي بن يوب" },
    { en: "Sidi Ali Boussidi", ar: "سيدي علي بوسيدي" },
    { en: "Sidi Bel-Abbes", ar: "سيدي بلعباس" },
    { en: "Sidi Brahim", ar: "سيدي ابراهيم" },
    { en: "Sidi Chaib", ar: "سيدي شعيب" },
    { en: "Sidi Dahou Zairs", ar: "سيدي دحو الزاير" },
    { en: "Sidi Hamadouche", ar: "سيدي حمادوش" },
    { en: "Sidi Khaled", ar: "سيدي خالد" },
    { en: "Sidi Lahcene", ar: "سيدي لحسن" },
    { en: "Sidi Yacoub", ar: "سيدي يعقوب" },
    { en: "Tabia", ar: "طابية" },
    { en: "Taoudmout", ar: "تاودموت" },
    { en: "Tefessour", ar: "تفسور" },
    { en: "Teghalimet", ar: "تغاليمت" },
    { en: "Telagh", ar: "تلاغ" },
    { en: "Tenira", ar: "تنيرة" },
    { en: "Tessala", ar: "تسالة" },
    { en: "Tilmouni", ar: "تلموني" },
    { en: "Zerouala", ar: "زروالة" },
  ],
  "23": [
    { en: "Ain El Berda", ar: "عين الباردة" },
    { en: "Annaba", ar: "عنابة" },
    { en: "Berrahal", ar: "برحال" },
    { en: "Chetaibi", ar: "شطايبي" },
    { en: "Cheurfa", ar: "الشرفة" },
    { en: "El Bouni", ar: "البوني" },
    { en: "El Eulma", ar: "العلمة" },
    { en: "El Hadjar", ar: "الحجار" },
    { en: "Oued El Aneb", ar: "واد العنب" },
    { en: "Seraidi", ar: "سرايدي" },
    { en: "Sidi Amar", ar: "سيدي عمار" },
    { en: "Treat", ar: "التريعات" },
  ],
  "24": [
    { en: "Ain Ben Beida", ar: "عين بن بيضاء" },
    { en: "Ain Larbi", ar: "عين العربي" },
    { en: "Ain Makhlouf", ar: "عين مخلوف" },
    { en: "Ain Regada", ar: "عين رقادة" },
    { en: "Ain Sandel", ar: "عين صندل" },
    { en: "Belkheir", ar: "بلخير" },
    { en: "Bendjarah", ar: "بن جراح" },
    { en: "Beni Mezline", ar: "بني مزلين" },
    { en: "Bordj Sabath", ar: "برج صباط" },
    { en: "Bou Hachana", ar: "بوحشانة" },
    { en: "Bou Hamdane", ar: "بوحمدان" },
    { en: "Bouati Mahmoud", ar: "بوعاتي محمود" },
    { en: "Bouchegouf", ar: "بوشقوف" },
    { en: "Boumahra Ahmed", ar: "بومهرة أحمد" },
    { en: "Dahouara", ar: "الدهوارة" },
    { en: "Djeballah Khemissi", ar: "جبالة الخميسي" },
    { en: "El Fedjoudj", ar: "الفجوج" },
    { en: "Guelaat Bou Sbaa", ar: "قلعة بوصبع" },
    { en: "Guelma", ar: "قالمة" },
    { en: "Hammam Debagh", ar: "حمام دباغ" },
    { en: "Hammam N'bail", ar: "حمام النبايل" },
    { en: "Heliopolis", ar: "هيليوبوليس" },
    { en: "Houari Boumedienne", ar: "هواري بومدين" },
    { en: "Khezaras", ar: "لخزارة" },
    { en: "Medjez Amar", ar: "مجاز عمار" },
    { en: "Medjez Sfa", ar: "مجاز الصفاء" },
    { en: "Nechmaya", ar: "نشماية" },
    { en: "Oued Cheham", ar: "وادي الشحم" },
    { en: "Oued Ferragha", ar: "وادي فراغة" },
    { en: "Oued Zenati", ar: "وادي الزناتي" },
    { en: "Ras El Agba", ar: "رأس العقبة" },
    { en: "Roknia", ar: "الركنية" },
    { en: "Sellaoua Announa", ar: "سلاوة عنونة" },
    { en: "Tamlouka", ar: "تاملوكة" },
  ],
  "25": [
    { en: "Ain Abid", ar: "عين عبيد" },
    { en: "Ain Smara", ar: "عين السمارة" },
    { en: "Ben Badis", ar: "أبن باديس الهرية" },
    { en: "Beni Hamidane", ar: "بني حميدان" },
    { en: "Constantine", ar: "قسنطينة" },
    { en: "Didouche Mourad", ar: "ديدوش مراد" },
    { en: "El Khroub", ar: "الخروب" },
    { en: "Hamma Bouziane", ar: "حامة بوزيان" },
    { en: "Ibn Ziad", ar: "ابن زياد" },
    { en: "Messaoud Boudjeriou", ar: "بوجريو مسعود" },
    { en: "Ouled Rahmoun", ar: "أولاد رحمون" },
    { en: "Zighoud Youcef", ar: "زيغود يوسف" },
  ],
  "26": [
    { en: "Ain Boucif", ar: "عين بوسيف" },
    { en: "Ain Ouksir", ar: "عين اقصير" },
    { en: "Aissaouia", ar: "العيساوية" },
    { en: "Aziz", ar: "عزيز" },
    { en: "Baata", ar: "بعطة" },
    { en: "Ben Chicao", ar: "بن شكاو" },
    { en: "Beni Slimane", ar: "بني سليمان" },
    { en: "Berrouaghia", ar: "البرواقية" },
    { en: "Bir Ben Laabed", ar: "بئر بن عابد" },
    { en: "Boghar", ar: "بوغار" },
    { en: "Bouaiche", ar: "بوعيش" },
    { en: "Bouaichoune", ar: "بوعيشون" },
    { en: "Bouchrahil", ar: "بوشراحيل" },
    { en: "Boughzoul", ar: "بوغزول" },
    { en: "Bouskene", ar: "بوسكن" },
    { en: "Chabounia", ar: "الشهبونية" },
    { en: "Chelalet El Adhaoura", ar: "شلالة العذاورة" },
    { en: "Cheniguel", ar: "شنيقل" },
    { en: "Derrag", ar: "دراق" },
    { en: "Djouab", ar: "جواب" },
    { en: "Draa Esmar", ar: "ذراع السمار" },
    { en: "El Azizia", ar: "العزيزية" },
    { en: "El Guelbelkebir", ar: "القلب الكبير" },
    { en: "El Hamdania", ar: "الحمدانية" },
    { en: "El Haoudane", ar: "الحوضان" },
    { en: "El Omaria", ar: "العمارية" },
    { en: "El Ouinet", ar: "العوينات" },
    { en: "Hannacha", ar: "حناشة" },
    { en: "Kef Lakhdar", ar: "الكاف الاخضر" },
    { en: "Khams Djouamaa", ar: "خمس جوامع" },
    { en: "Ksar El Boukhari", ar: "قصر البخاري" },
    { en: "M'fatha", ar: "مفاتحة" },
    { en: "Maghraoua", ar: "مغراوة" },
    { en: "Medea", ar: "المدية" },
    { en: "Medjebar", ar: "مجبر" },
    { en: "Mezerana", ar: "مزغنة" },
    { en: "Mihoub", ar: "ميهوب" },
    { en: "Ouamri", ar: "عوامري" },
    { en: "Oued Harbil", ar: "وادي حربيل" },
    { en: "Ouled Antar", ar: "أولاد عنتر" },
    { en: "Ouled Bouachra", ar: "أولاد بوعشرة" },
    { en: "Ouled Brahim", ar: "أولاد إبراهيم" },
    { en: "Ouled Deid", ar: "أولاد دايد" },
    { en: "Ouled Emaaraf", ar: "أولاد امعرف" },
    { en: "Ouled Hellal", ar: "أولاد هلال" },
    { en: "Oum El Djellil", ar: "أم الجليل" },
    { en: "Ouzera", ar: "وزرة" },
    { en: "Rebaia", ar: "الربعية" },
    { en: "Saneg", ar: "السانق" },
    { en: "Sedraya", ar: "سدراية" },
    { en: "Seghouane", ar: "سغوان" },
    { en: "Si Mahdjoub", ar: "سي المحجوب" },
    { en: "Sidi Demed", ar: "سيدي دامد" },
    { en: "Sidi Naamane", ar: "سيدي نعمان" },
    { en: "Sidi Rabie", ar: "سيدي الربيع" },
    { en: "Sidi Zahar", ar: "سيدي زهار" },
    { en: "Sidi Ziane", ar: "سيدي زيان" },
    { en: "Souagui", ar: "السواقي" },
    { en: "Tablat", ar: "تابلاط" },
    { en: "Tafraout", ar: "تفراوت" },
    { en: "Tamesguida", ar: "تمسقيدة" },
    { en: "Tizi Mahdi", ar: "تيزي مهدي" },
    { en: "Tletat Ed Douair", ar: "ثلاث دوائر" },
    { en: "Zoubiria", ar: "الزبيرية" },
  ],
  "27": [
    { en: "Achaacha", ar: "عشعاشة" },
    { en: "Ain-Boudinar", ar: "عين بودينار" },
    { en: "Ain-Nouissy", ar: "عين نويسي" },
    { en: "Ain-Sidi Cherif", ar: "عين سيدي الشريف" },
    { en: "Ain-Tedles", ar: "عين تادلس" },
    { en: "Benabdelmalek Ramdane", ar: "بن عبد المالك رمضان" },
    { en: "Bouguirat", ar: "بوقيراط" },
    { en: "Fornaka", ar: "فرناقة" },
    { en: "Hadjadj", ar: "حجاج" },
    { en: "Hassi Mameche", ar: "حاسي ماماش" },
    { en: "Hassiane", ar: "الحسيان (بني ياحي" },
    { en: "Khadra", ar: "خضرة" },
    { en: "Kheir-Eddine", ar: "خير الدين" },
    { en: "Mansourah", ar: "منصورة" },
    { en: "Mazagran", ar: "مزغران" },
    { en: "Mesra", ar: "ماسرة" },
    { en: "Mostaganem", ar: "مستغانم" },
    { en: "Nekmaria", ar: "نكمارية" },
    { en: "Oued El Kheir", ar: "وادي الخير" },
    { en: "Ouled Boughalem", ar: "أولاد بوغالم" },
    { en: "Ouled-Maalah", ar: "أولاد مع الله" },
    { en: "Safsaf", ar: "صفصاف" },
    { en: "Sayada", ar: "صيادة" },
    { en: "Sidi Ali", ar: "سيدي علي" },
    { en: "Sidi Belaattar", ar: "سيدي بلعطار" },
    { en: "Sidi-Lakhdar", ar: "سيدي لخضر" },
    { en: "Sirat", ar: "سيرات" },
    { en: "Souaflia", ar: "السوافلية" },
    { en: "Sour", ar: "سور" },
    { en: "Stidia", ar: "ستيدية" },
    { en: "Tazgait", ar: "تزقايت" },
    { en: "Touahria", ar: "الطواهرية" },
  ],
  "28": [
    { en: "Ain El Hadjel", ar: "عين الحجل" },
    { en: "Ain El Melh", ar: "عين الملح" },
    { en: "Ain Fares", ar: "عين فارس" },
    { en: "Ain Khadra", ar: "عين الخضراء" },
    { en: "Ain Rich", ar: "عين الريش" },
    { en: "Belaiba", ar: "بلعايبة" },
    { en: "Ben Srour", ar: "بن سرور" },
    { en: "Beni Ilmane", ar: "بني يلمان" },
    { en: "Benzouh", ar: "بن زوه" },
    { en: "Berhoum", ar: "برهوم" },
    { en: "Bir Foda", ar: "بئر فضة" },
    { en: "Bou Saada", ar: "بوسعادة" },
    { en: "Bouti Sayeh", ar: "بوطي السايح" },
    { en: "Chellal", ar: "شلال" },
    { en: "Dehahna", ar: "دهاهنة" },
    { en: "Djebel Messaad", ar: "جبل مساعد" },
    { en: "El Hamel", ar: "الهامل" },
    { en: "El Houamed", ar: "الحوامد" },
    { en: "Hammam Dalaa", ar: "حمام الضلعة" },
    { en: "Khettouti Sed-El-Jir", ar: "خطوطي سد الجير" },
    { en: "Khoubana", ar: "خبانة" },
    { en: "M'cif", ar: "مسيف" },
    { en: "M'sila", ar: "المسيلة" },
    { en: "M'tarfa", ar: "المطارفة" },
    { en: "Maadid", ar: "المعاضيد" },
    { en: "Maarif", ar: "معاريف" },
    { en: "Magra", ar: "مقرة" },
    { en: "Medjedel", ar: "امجدل" },
    { en: "Menaa", ar: "مناعة" },
    { en: "Mohamed Boudiaf", ar: "محمد بوضياف" },
    { en: "Ouanougha", ar: "ونوغة" },
    { en: "Ouled Addi Guebala", ar: "أولاد عدي لقبالة" },
    { en: "Ouled Derradj", ar: "أولاد دراج" },
    { en: "Ouled Madhi", ar: "أولاد ماضي" },
    { en: "Ouled Mansour", ar: "أولاد منصور" },
    { en: "Ouled Sidi Brahim", ar: "أولاد سيدي ابراهيم" },
    { en: "Ouled Slimane", ar: "أولاد سليمان" },
    { en: "Oulteme", ar: "ولتام" },
    { en: "Sidi Aissa", ar: "سيدي عيسى" },
    { en: "Sidi Ameur", ar: "سيدي عامر" },
    { en: "Sidi Hadjeres", ar: "سيدي هجرس" },
    { en: "Sidi M'hamed", ar: "سيدي امحمد" },
    { en: "Slim", ar: "سليم" },
    { en: "Souamaa", ar: "السوامع" },
    { en: "Tamsa", ar: "تامسة" },
    { en: "Tarmount", ar: "تارمونت" },
    { en: "Zarzour", ar: "زرزور" },
  ],
  "29": [
    { en: "Ain Fares", ar: "عين فارس" },
    { en: "Ain Fekan", ar: "عين فكان" },
    { en: "Ain Ferah", ar: "عين فراح" },
    { en: "Ain Frass", ar: "عين أفرص" },
    { en: "Alaimia", ar: "العلايمية" },
    { en: "Aouf", ar: "عوف" },
    { en: "Benian", ar: "بنيان" },
    { en: "Bou Henni", ar: "بوهني" },
    { en: "Bouhanifia", ar: "بوحنيفية" },
    { en: "Chorfa", ar: "الشرفاء" },
    { en: "El Bordj", ar: "البرج" },
    { en: "El Gaada", ar: "القعدة" },
    { en: "El Ghomri", ar: "الغمري" },
    { en: "El Gueitena", ar: "القطنة" },
    { en: "El Hachem", ar: "الحشم" },
    { en: "El Keurt", ar: "القرط" },
    { en: "El Mamounia", ar: "المأمونية" },
    { en: "El Menaouer", ar: "المنور" },
    { en: "Ferraguig", ar: "فراقيق" },
    { en: "Froha", ar: "فروحة" },
    { en: "Gharrous", ar: "غروس" },
    { en: "Ghriss", ar: "غريس" },
    { en: "Guerdjoum", ar: "قرجوم" },
    { en: "Hacine", ar: "حسين" },
    { en: "Khalouia", ar: "خلوية" },
    { en: "Makhda", ar: "ماقضة" },
    { en: "Maoussa", ar: "ماوسة" },
    { en: "Mascara", ar: "معسكر" },
    { en: "Matemore", ar: "المطمور" },
    { en: "Mocta-Douz", ar: "مقطع الدوز" },
    { en: "Mohammadia", ar: "المحمدية" },
    { en: "Nesmot", ar: "نسمط" },
    { en: "Oggaz", ar: "عقاز" },
    { en: "Oued El Abtal", ar: "وادي الأبطال" },
    { en: "Oued Taria", ar: "وادي التاغية" },
    { en: "Ras El Ain Amirouche", ar: "رأس عين عميروش" },
    { en: "Sedjerara", ar: "سجرارة" },
    { en: "Sehailia", ar: "السهايلية" },
    { en: "Sidi Abdeldjebar", ar: "سيدي عبد الجبار" },
    { en: "Sidi Abdelmoumene", ar: "سيدي عبد المومن" },
    { en: "Sidi Boussaid", ar: "سيدي بوسعيد" },
    { en: "Sidi Kada", ar: "سيدي قادة" },
    { en: "Sig", ar: "سيق" },
    { en: "Tighennif", ar: "تيغنيف" },
    { en: "Tizi", ar: "تيزي" },
    { en: "Zahana", ar: "زهانة" },
    { en: "Zelamta", ar: "زلامطة" },
  ],
  "30": [
    { en: "Ain Beida", ar: "عين البيضاء" },
    { en: "El Borma", ar: "البرمة" },
    { en: "Hassi Ben Abdellah", ar: "حاسي بن عبد الله" },
    { en: "Hassi Messaoud", ar: "حاسي مسعود" },
    { en: "N'goussa", ar: "انقوسة" },
    { en: "Ouargla", ar: "ورقلة" },
    { en: "Rouissat", ar: "الرويسات" },
    { en: "Sidi Khouiled", ar: "سيدي خويلد" },
  ],
  "31": [
    { en: "Ain Biya", ar: "عين البية" },
    { en: "Ain Kerma", ar: "عين الكرمة" },
    { en: "Ain Turk", ar: "عين الترك" },
    { en: "Arzew", ar: "أرزيو" },
    { en: "Ben Freha", ar: "بن فريحة" },
    { en: "Bethioua", ar: "بطيوة" },
    { en: "Bir El Djir", ar: "بئر الجير" },
    { en: "Boufatis", ar: "بوفاتيس" },
    { en: "Bousfer", ar: "بوسفر" },
    { en: "Boutlelis", ar: "بوتليليس" },
    { en: "El Ancor", ar: "العنصر" },
    { en: "El Braya", ar: "البراية" },
    { en: "El Kerma", ar: "الكرمة" },
    { en: "Es Senia", ar: "السانية" },
    { en: "Gdyel", ar: "قديل" },
    { en: "Hassi Ben Okba", ar: "حاسي بن عقبة" },
    { en: "Hassi Bounif", ar: "حاسي بونيف" },
    { en: "Hassi Mefsoukh", ar: "حاسي مفسوخ" },
    { en: "Marsat El Hadjadj", ar: "مرسى الحجاج" },
    { en: "Mers El Kebir", ar: "المرسى الكبير" },
    { en: "Messerghin", ar: "مسرغين" },
    { en: "Oran", ar: "وهران" },
    { en: "Oued Tlelat", ar: "وادي تليلات" },
    { en: "Sidi Ben Yebka", ar: "سيدي بن يبقى" },
    { en: "Sidi Chami", ar: "سيدي الشحمي" },
    { en: "Tafraoui", ar: "طفراوي" },
  ],
  "32": [
    { en: "Ain El Orak", ar: "عين العراك" },
    { en: "Arbaouat", ar: "اربوات" },
    { en: "Boualem", ar: "بوعلام" },
    { en: "Bougtoub", ar: "بوقطب" },
    { en: "Boussemghoun", ar: "بوسمغون" },
    { en: "Brezina", ar: "بريزينة" },
    { en: "Cheguig", ar: "الشقيق" },
    { en: "Chellala", ar: "شلالة" },
    { en: "El Bayadh", ar: "البيض" },
    { en: "El Bnoud", ar: "البنود" },
    { en: "El Kheiter", ar: "الخيثر" },
    { en: "El Mehara", ar: "المحرة" },
    { en: "Ghassoul", ar: "الغاسول" },
    { en: "Kef El Ahmar", ar: "الكاف الأحمر" },
    { en: "Krakda", ar: "كراكدة" },
    { en: "Labiodh Sidi Cheikh", ar: "الأبيض سيدي الشيخ" },
    { en: "Rogassa", ar: "رقاصة" },
    { en: "Sidi Ameur", ar: "سيدي عامر" },
    { en: "Sidi Slimane", ar: "سيدي سليمان" },
    { en: "Sidi Tiffour", ar: "سيدي طيفور" },
    { en: "Stitten", ar: "ستيتن" },
    { en: "Tousmouline", ar: "توسمولين" },
  ],
  "33": [
    { en: "Bordj Omar Driss", ar: "برج عمر إدريس" },
    { en: "Debdeb", ar: "دبداب" },
    { en: "Illizi", ar: "إيليزي" },
    { en: "In Amenas", ar: "إن أمناس" },
  ],
  "34": [
    { en: "Ain Taghrout", ar: "عين تاغروت" },
    { en: "Ain Tesra", ar: "عين تسرة" },
    { en: "B. B. Arreridj", ar: "برج بوعريرج" },
    { en: "Belimour", ar: "بليمور" },
    { en: "Ben Daoud", ar: "بن داود" },
    { en: "Bir Kasdali", ar: "بئر قاصد علي" },
    { en: "Bordj Ghedir", ar: "برج الغدير" },
    { en: "Bordj Zemmoura", ar: "برج زمورة" },
    { en: "Colla", ar: "القلة" },
    { en: "Djaafra", ar: "جعافرة" },
    { en: "El Achir", ar: "الياشير" },
    { en: "El Annasseur", ar: "العناصر" },
    { en: "El Euch", ar: "العش" },
    { en: "El M'hir", ar: "المهير" },
    { en: "El Main", ar: "الماين" },
    { en: "Elhammadia", ar: "الحمادية" },
    { en: "Ghailasa", ar: "غيلاسة" },
    { en: "Haraza", ar: "حرازة" },
    { en: "Hasnaoua", ar: "حسناوة" },
    { en: "Khelil", ar: "خليل" },
    { en: "Ksour", ar: "القصور" },
    { en: "Mansoura", ar: "المنصورة" },
    { en: "Medjana", ar: "مجانة" },
    { en: "Ouled Brahem", ar: "أولاد أبراهم" },
    { en: "Ouled Dahmane", ar: "أولاد دحمان" },
    { en: "Ouled Sidi-Brahim", ar: "أولاد سيدي ابراهيم" },
    { en: "Rabta", ar: "الرابطة" },
    { en: "Ras El Oued", ar: "رأس الوادي" },
    { en: "Sidi-Embarek", ar: "سيدي أمبارك" },
    { en: "Taglait", ar: "تقلعيت" },
    { en: "Tassamert", ar: "تسامرت" },
    { en: "Tefreg", ar: "تفرق" },
    { en: "Teniet En Nasr", ar: "ثنية النصر" },
    { en: "Tixter", ar: "تيكستار" },
  ],
  "35": [
    { en: "Afir", ar: "أعفير" },
    { en: "Ammal", ar: "عمال" },
    { en: "Baghlia", ar: "بغلية" },
    { en: "Ben Choud", ar: "بن شود" },
    { en: "Beni Amrane", ar: "بني عمران" },
    { en: "Bordj Menaiel", ar: "برج منايل" },
    { en: "Boudouaou", ar: "بودواو" },
    { en: "Boudouaou El Bahri", ar: "بودواو البحري" },
    { en: "Boumerdes", ar: "بومرداس" },
    { en: "Bouzegza Keddara", ar: "بوزقزة قدارة" },
    { en: "Chabet El Ameur", ar: "شعبة العامر" },
    { en: "Corso", ar: "قورصو" },
    { en: "Dellys", ar: "دلس" },
    { en: "Djinet", ar: "جنات" },
    { en: "El Kharrouba", ar: "الخروبة" },
    { en: "Hammedi", ar: "حمادي" },
    { en: "Isser", ar: "يسر" },
    { en: "Khemis El Khechna", ar: "خميس الخشنة" },
    { en: "Larbatache", ar: "الاربعطاش" },
    { en: "Leghata", ar: "لقاطة" },
    { en: "Naciria", ar: "الناصرية" },
    { en: "Ouled Aissa", ar: "أولاد عيسى" },
    { en: "Ouled Hedadj", ar: "أولاد هداج" },
    { en: "Ouled Moussa", ar: "أولاد موسى" },
    { en: "Si Mustapha", ar: "سي مصطفى" },
    { en: "Sidi Daoud", ar: "سيدي داود" },
    { en: "Souk El Had", ar: "سوق الحد" },
    { en: "Taourga", ar: "تاورقة" },
    { en: "Thenia", ar: "الثنية" },
    { en: "Tidjelabine", ar: "تيجلابين" },
    { en: "Timezrit", ar: "تيمزريت" },
    { en: "Zemmouri", ar: "زموري" },
  ],
  "36": [
    { en: "Ain El Assel", ar: "عين العسل" },
    { en: "Ain Kerma", ar: "عين الكرمة" },
    { en: "Asfour", ar: "عصفور" },
    { en: "Ben M Hidi", ar: "بن مهيدي" },
    { en: "Berrihane", ar: "بريحان" },
    { en: "Besbes", ar: "البسباس" },
    { en: "Bougous", ar: "بوقوس" },
    { en: "Bouhadjar", ar: "بوحجار" },
    { en: "Bouteldja", ar: "بوثلجة" },
    { en: "Chebaita Mokhtar", ar: "شبيطة مختار" },
    { en: "Chefia", ar: "الشافية" },
    { en: "Chihani", ar: "شحاني" },
    { en: "Drean", ar: "الذرعـان" },
    { en: "Echatt", ar: "الشط" },
    { en: "El Aioun", ar: "العيون" },
    { en: "El Kala", ar: "القالة" },
    { en: "El Tarf", ar: "الطارف" },
    { en: "Hammam Beni Salah", ar: "حمام بني صالح" },
    { en: "Lac Des Oiseaux", ar: "بحيرة الطيور" },
    { en: "Oued Zitoun", ar: "وادي الزيتون" },
    { en: "Raml Souk", ar: "رمل السوق" },
    { en: "Souarekh", ar: "السوارخ" },
    { en: "Zerizer", ar: "زريزر" },
    { en: "Zitouna", ar: "الزيتونة" },
  ],
  "37": [
    { en: "Oum El Assel", ar: "أم العسل" },
    { en: "Tindouf", ar: "تندوف" },
  ],
  "38": [
    { en: "Ammari", ar: "عماري" },
    { en: "Beni Chaib", ar: "بني شعيب" },
    { en: "Beni Lahcene", ar: "بني لحسن" },
    { en: "Bordj Bounaama", ar: "برج بونعامة" },
    { en: "Bordj El Emir Abdelkader", ar: "برج الأمير عبد القادر" },
    { en: "Boucaid", ar: "بوقائد" },
    { en: "Khemisti", ar: "خميستي" },
    { en: "Larbaa", ar: "الأربعاء" },
    { en: "Lardjem", ar: "لرجام" },
    { en: "Layoune", ar: "العيون" },
    { en: "Lazharia", ar: "الأزهرية" },
    { en: "Maacem", ar: "المعاصم" },
    { en: "Melaab", ar: "الملعب" },
    { en: "Ouled Bessam", ar: "أولاد بسام" },
    { en: "Sidi Abed", ar: "سيدي عابد" },
    { en: "Sidi Boutouchent", ar: "سيدي بوتوشنت" },
    { en: "Sidi Lantri", ar: "سيدي العنتري" },
    { en: "Sidi Slimane", ar: "سيدي سليمان" },
    { en: "Tamellahet", ar: "تملاحت" },
    { en: "Theniet El Had", ar: "ثنية الاحد" },
    { en: "Tissemsilt", ar: "تيسمسيلت" },
    { en: "Youssoufia", ar: "اليوسفية" },
  ],
  "39": [
    { en: "Bayadha", ar: "البياضة" },
    { en: "Ben Guecha", ar: "بن  قشة" },
    { en: "Debila", ar: "الدبيلة" },
    { en: "Douar El Maa", ar: "دوار الماء" },
    { en: "El Ogla", ar: "العقلة" },
    { en: "El-Oued", ar: "الوادي" },
    { en: "Guemar", ar: "قمار" },
    { en: "Hamraia", ar: "الحمراية" },
    { en: "Hassani Abdelkrim", ar: "حساني عبد الكريم" },
    { en: "Hassi Khalifa", ar: "حاسي خليفة" },
    { en: "Kouinine", ar: "كوينين" },
    { en: "Magrane", ar: "المقرن" },
    { en: "Mih Ouansa", ar: "اميه وانسة" },
    { en: "Nakhla", ar: "النخلة" },
    { en: "Oued El Alenda", ar: "وادي العلندة" },
    { en: "Ourmes", ar: "ورماس" },
    { en: "Reguiba", ar: "الرقيبة" },
    { en: "Robbah", ar: "الرباح" },
    { en: "Sidi Aoun", ar: "سيدي عون" },
    { en: "Taghzout", ar: "تغزوت" },
    { en: "Taleb Larbi", ar: "الطالب العربي" },
    { en: "Trifaoui", ar: "الطريفاوي" },
  ],
  "40": [
    { en: "Ain Touila", ar: "عين الطويلة" },
    { en: "Babar", ar: "بابار" },
    { en: "Baghai", ar: "بغاي" },
    { en: "Bouhmama", ar: "بوحمامة" },
    { en: "Chechar", ar: "ششار" },
    { en: "Chelia", ar: "شلية" },
    { en: "Djellal", ar: "جلال" },
    { en: "El Hamma", ar: "الحامة" },
    { en: "El Mahmal", ar: "المحمل" },
    { en: "El Oueldja", ar: "الولجة" },
    { en: "Ensigha", ar: "انسيغة" },
    { en: "Kais", ar: "قايس" },
    { en: "Khenchela", ar: "خنشلة" },
    { en: "Khirane", ar: "خيران" },
    { en: "M'sara", ar: "مصارة" },
    { en: "M'toussa", ar: "متوسة" },
    { en: "Ouled Rechache", ar: "أولاد رشاش" },
    { en: "Remila", ar: "الرميلة" },
    { en: "Tamza", ar: "طامزة" },
    { en: "Taouzianat", ar: "تاوزيانت" },
    { en: "Yabous", ar: "يابوس" },
  ],
  "41": [
    { en: "Ain Soltane", ar: "عين سلطان" },
    { en: "Ain Zana", ar: "عين الزانة" },
    { en: "Bir Bouhouche", ar: "بئر بوحوش" },
    { en: "Drea", ar: "الدريعة" },
    { en: "Haddada", ar: "الحدادة" },
    { en: "Hanencha", ar: "الحنانشة" },
    { en: "Khedara", ar: "الخضارة" },
    { en: "Khemissa", ar: "خميسة" },
    { en: "M'daourouche", ar: "مداوروش" },
    { en: "Machroha", ar: "المشروحة" },
    { en: "Merahna", ar: "المراهنة" },
    { en: "Oued Kebrit", ar: "وادي الكبريت" },
    { en: "Ouillen", ar: "ويلان" },
    { en: "Ouled Driss", ar: "أولاد إدريس" },
    { en: "Ouled Moumen", ar: "أولاد مومن" },
    { en: "Oum El Adhaim", ar: "أم العظايم" },
    { en: "Ragouba", ar: "الراقوبة" },
    { en: "Safel El Ouiden", ar: "سافل الويدان" },
    { en: "Sedrata", ar: "سدراتة" },
    { en: "Sidi Fredj", ar: "سيدي فرج" },
    { en: "Souk Ahras", ar: "سوق أهراس" },
    { en: "Taoura", ar: "تاورة" },
    { en: "Terraguelt", ar: "ترقالت" },
    { en: "Tiffech", ar: "تيفاش" },
    { en: "Zaarouria", ar: "الزعرورية" },
    { en: "Zouabi", ar: "الزوابي" },
  ],
  "42": [
    { en: "Aghbal", ar: "أغبال" },
    { en: "Ahmer El Ain", ar: "أحمر العين" },
    { en: "Ain Tagourait", ar: "عين تاقورايت" },
    { en: "Attatba", ar: "الحطاطبة" },
    { en: "Beni Mileuk", ar: "بني ميلك" },
    { en: "Bou Haroun", ar: "بوهارون" },
    { en: "Bou Ismail", ar: "بواسماعيل" },
    { en: "Bourkika", ar: "بورقيقة" },
    { en: "Chaiba", ar: "الشعيبة" },
    { en: "Cherchell", ar: "شرشال" },
    { en: "Damous", ar: "الداموس" },
    { en: "Douaouda", ar: "دواودة" },
    { en: "Fouka", ar: "فوكة" },
    { en: "Gouraya", ar: "قوراية" },
    { en: "Hadjout", ar: "حجوط" },
    { en: "Hadjret Ennous", ar: "حجرة النص" },
    { en: "Khemisti", ar: "خميستي" },
    { en: "Kolea", ar: "القليعة" },
    { en: "Larhat", ar: "الأرهاط" },
    { en: "Menaceur", ar: "مناصر" },
    { en: "Merad", ar: "مراد" },
    { en: "Messelmoun", ar: "مسلمون" },
    { en: "Nador", ar: "الناظور" },
    { en: "Sidi Ghiles", ar: "سيدي غيلاس" },
    { en: "Sidi Rached", ar: "سيدي راشد" },
    { en: "Sidi Semiane", ar: "سيدي سميان" },
    { en: "Sidi-Amar", ar: "سيدي عامر" },
    { en: "Tipaza", ar: "تيبازة" },
  ],
  "43": [
    { en: "Ahmed Rachedi", ar: "أحمد راشدي" },
    { en: "Ain Beida Harriche", ar: "عين البيضاء أحريش" },
    { en: "Ain Mellouk", ar: "عين الملوك" },
    { en: "Ain Tine", ar: "عين التين" },
    { en: "Amira Arres", ar: "اعميرة اراس" },
    { en: "Benyahia Abderrahmane", ar: "بن يحي عبد الرحمن" },
    { en: "Bouhatem", ar: "بوحاتم" },
    { en: "Chelghoum Laid", ar: "شلغوم العيد" },
    { en: "Chigara", ar: "الشيقارة" },
    { en: "Derrahi Bousselah", ar: "دراحي بوصلاح" },
    { en: "El Ayadi Barbes", ar: "العياضي برباس" },
    { en: "El Mechira", ar: "مشيرة" },
    { en: "Ferdjioua", ar: "فرجيوة" },
    { en: "Grarem Gouga", ar: "القرارم قوقة" },
    { en: "Hamala", ar: "حمالة" },
    { en: "Mila", ar: "ميلة" },
    { en: "Minar Zarza", ar: "مينار زارزة" },
    { en: "Oued Athmenia", ar: "وادي العثمانية" },
    { en: "Oued Endja", ar: "وادي النجاء" },
    { en: "Oued Seguen", ar: "وادي سقان" },
    { en: "Ouled Khalouf", ar: "أولاد اخلوف" },
    { en: "Rouached", ar: "الرواشد" },
    { en: "Sidi Khelifa", ar: "سيدي خليفة" },
    { en: "Sidi Merouane", ar: "سيدي مروان" },
    { en: "Tadjenanet", ar: "تاجنانت" },
    { en: "Tassadane Haddada", ar: "تسدان حدادة" },
    { en: "Tassala Lematai", ar: "تسالة لمطاعي" },
    { en: "Teleghma", ar: "التلاغمة" },
    { en: "Terrai Bainen", ar: "ترعي باينان" },
    { en: "Tiberguent", ar: "تيبرقنت" },
    { en: "Yahia Beniguecha", ar: "يحي بني قشة" },
    { en: "Zeghaia", ar: "زغاية" },
  ],
  "44": [
    { en: "Ain-Benian", ar: "عين البنيان" },
    { en: "Ain-Bouyahia", ar: "عين بويحيى" },
    { en: "Ain-Defla", ar: "عين الدفلى" },
    { en: "Ain-Lechiakh", ar: "عين الاشياخ" },
    { en: "Ain-Soltane", ar: "عين السلطان" },
    { en: "Ain-Torki", ar: "عين التركي" },
    { en: "Arib", ar: "عريب" },
    { en: "Bathia", ar: "بطحية" },
    { en: "Belaas", ar: "بلعاص" },
    { en: "Ben Allal", ar: "بن علال" },
    { en: "Bir-Ould-Khelifa", ar: "بئر ولد خليفة" },
    { en: "Birbouche", ar: "بربوش" },
    { en: "Bordj-Emir-Khaled", ar: "برج الأمير خالد" },
    { en: "Boumedfaa", ar: "بومدفع" },
    { en: "Bourached", ar: "بوراشد" },
    { en: "Djelida", ar: "جليدة" },
    { en: "Djemaa Ouled Cheikh", ar: "جمعة أولاد الشيخ" },
    { en: "Djendel", ar: "جندل" },
    { en: "El-Abadia", ar: "العبادية" },
    { en: "El-Amra", ar: "العامرة" },
    { en: "El-Attaf", ar: "العطاف" },
    { en: "El-Maine", ar: "الماين" },
    { en: "Hammam-Righa", ar: "حمام ريغة" },
    { en: "Hassania", ar: "الحسانية" },
    { en: "Hoceinia", ar: "الحسينية" },
    { en: "Khemis-Miliana", ar: "خميس مليانة" },
    { en: "Mekhatria", ar: "المخاطرية" },
    { en: "Miliana", ar: "مليانة" },
    { en: "Oued Chorfa", ar: "وادي الشرفاء" },
    { en: "Oued Djemaa", ar: "واد الجمعة" },
    { en: "Rouina", ar: "الروينة" },
    { en: "Sidi-Lakhdar", ar: "سيدي الأخضر" },
    { en: "Tacheta Zegagha", ar: "تاشتة زقاغة" },
    { en: "Tarik-Ibn-Ziad", ar: "طارق بن زياد" },
    { en: "Tiberkanine", ar: "تبركانين" },
    { en: "Zeddine", ar: "زدين" },
  ],
  "45": [
    { en: "Ain Ben Khelil", ar: "عين بن خليل" },
    { en: "Ain Sefra", ar: "عين الصفراء" },
    { en: "Asla", ar: "عسلة" },
    { en: "Djenienne Bourezg", ar: "جنين بورزق" },
    { en: "El Biodh", ar: "البيوض" },
    { en: "Kasdir", ar: "القصدير" },
    { en: "Makmen Ben Amar", ar: "مكمن بن عمار" },
    { en: "Mecheria", ar: "المشرية" },
    { en: "Moghrar", ar: "مغرار" },
    { en: "Naama", ar: "النعامة" },
    { en: "Sfissifa", ar: "سفيسيفة" },
    { en: "Tiout", ar: "تيوت" },
  ],
  "46": [
    { en: "Aghlal", ar: "أغلال" },
    { en: "Ain El Arbaa", ar: "عين الأربعاء" },
    { en: "Ain Kihal", ar: "عين الكيحل" },
    { en: "Ain Temouchent", ar: "عين تموشنت" },
    { en: "Ain Tolba", ar: "عين الطلبة" },
    { en: "Aoubellil", ar: "عقب الليل" },
    { en: "Beni Saf", ar: "بني صاف" },
    { en: "Bouzedjar", ar: "بوزجار" },
    { en: "Chaabat El Ham", ar: "شعبة اللحم" },
    { en: "Chentouf", ar: "شنتوف" },
    { en: "El Amria", ar: "العامرية" },
    { en: "El Maleh", ar: "المالح" },
    { en: "El Messaid", ar: "المساعيد" },
    { en: "Emir Abdelkader", ar: "الأمير عبد القادر" },
    { en: "Hammam Bou Hadjar", ar: "حمام بوحجر" },
    { en: "Hassasna", ar: "الحساسنة" },
    { en: "Hassi El Ghella", ar: "حاسي الغلة" },
    { en: "Oued Berkeche", ar: "وادي برقش" },
    { en: "Oued Sebbah", ar: "وادي الصباح" },
    { en: "Ouled Boudjemaa", ar: "أولاد بوجمعة" },
    { en: "Ouled Kihal", ar: "أولاد الكيحل" },
    { en: "Oulhaca El Gheraba", ar: "ولهاصة الغرابة" },
    { en: "Sidi Ben Adda", ar: "سيدي بن عدة" },
    { en: "Sidi Boumediene", ar: "سيدي بومدين" },
    { en: "Sidi Ouriache", ar: "سيدي ورياش" },
    { en: "Sidi Safi", ar: "سيدي صافي" },
    { en: "Tamzoura", ar: "تامزورة" },
    { en: "Terga", ar: "تارقة" },
  ],
  "47": [
    { en: "Berriane", ar: "بريان" },
    { en: "Bounoura", ar: "بونورة" },
    { en: "Dhayet Bendhahoua", ar: "ضاية بن ضحوة" },
    { en: "El Atteuf", ar: "العطف" },
    { en: "El Guerrara", ar: "القرارة" },
    { en: "Ghardaia", ar: "غرداية" },
    { en: "Mansoura", ar: "المنصورة" },
    { en: "Metlili", ar: "متليلي" },
    { en: "Sebseb", ar: "سبسب" },
    { en: "Zelfana", ar: "زلفانة" },
  ],
  "48": [
    { en: "Ain Rahma", ar: "عين الرحمة" },
    { en: "Ain-Tarek", ar: "عين طارق" },
    { en: "Ammi Moussa", ar: "عمي موسى" },
    { en: "Belaassel Bouzagza", ar: "بلعسل بوزقزة" },
    { en: "Bendaoud", ar: "بن داود" },
    { en: "Beni Dergoun", ar: "بني درقن" },
    { en: "Beni Zentis", ar: "بني زنطيس" },
    { en: "Dar Ben Abdelah", ar: "دار بن عبد الله" },
    { en: "Djidiouia", ar: "جديوية" },
    { en: "El H'madna", ar: "الحمادنة" },
    { en: "El Hassi", ar: "الحاسي" },
    { en: "El Ouldja", ar: "الولجة" },
    { en: "El-Guettar", ar: "القطار" },
    { en: "El-Matmar", ar: "المطمر" },
    { en: "Had Echkalla", ar: "حد الشكالة" },
    { en: "Hamri", ar: "حمري" },
    { en: "Kalaa", ar: "القلعة" },
    { en: "Lahlef", ar: "لحلاف" },
    { en: "Mazouna", ar: "مازونة" },
    { en: "Mediouna", ar: "مديونة" },
    { en: "Mendes", ar: "منداس" },
    { en: "Merdja Sidi Abed", ar: "مرجة سيدي عابد" },
    { en: "Ouarizane", ar: "واريزان" },
    { en: "Oued El Djemaa", ar: "وادي الجمعة" },
    { en: "Oued Essalem", ar: "وادي السلام" },
    { en: "Oued-Rhiou", ar: "وادي رهيو" },
    { en: "Ouled Aiche", ar: "أولاد يعيش" },
    { en: "Ouled Sidi Mihoub", ar: "أولاد سيدي الميهوب" },
    { en: "Ramka", ar: "الرمكة" },
    { en: "Relizane", ar: "غليزان" },
    { en: "Sidi Khettab", ar: "سيدي  خطاب" },
    { en: "Sidi Lazreg", ar: "سيدي لزرق" },
    { en: "Sidi M'hamed Benali", ar: "سيدي أمحمد بن علي" },
    { en: "Sidi M'hamed Benaouda", ar: "سيدي امحمد بن عودة" },
    { en: "Sidi Saada", ar: "سيدي سعادة" },
    { en: "Souk El Had", ar: "سوق الحد" },
    { en: "Yellel", ar: "يلل" },
    { en: "Zemmoura", ar: "زمورة" },
  ],
  "49": [
    { en: "Aougrout", ar: "أوقروت" },
    { en: "Charouine", ar: "شروين" },
    { en: "Deldoul", ar: "دلدول" },
    { en: "Ksar Kaddour", ar: "قصر قدور" },
    { en: "Metarfa", ar: "المطارفة" },
    { en: "Ouled Aissa", ar: "أولاد عيسى" },
    { en: "Ouled Said", ar: "أولاد السعيد" },
    { en: "Talmine", ar: "طالمين" },
    { en: "Timimoun", ar: "تيميمون" },
    { en: "Tinerkouk", ar: "تنركوك" },
  ],
  "50": [
    { en: "Bordj Badji Mokhtar", ar: "برج باجي مختار" },
    { en: "Timiaouine", ar: "تيمياوين" },
  ],
  "51": [
    { en: "Besbes", ar: "بسباس" },
    { en: "Chaiba", ar: "الشعيبة" },
    { en: "Doucen", ar: "الدوسن" },
    { en: "Ouled Djellal", ar: "أولاد جلال" },
    { en: "Ras El Miad", ar: "رأس الميعاد" },
    { en: "Sidi Khaled", ar: "سيدي  خالد" },
  ],
  "52": [
    { en: "Beni-Abbes", ar: "بني عباس" },
    { en: "Beni-Ikhlef", ar: "بن يخلف" },
    { en: "El Ouata", ar: "الواتة" },
    { en: "Igli", ar: "إقلي" },
    { en: "Kerzaz", ar: "كرزاز" },
    { en: "Ksabi", ar: "القصابي" },
    { en: "Ouled-Khodeir", ar: "أولاد خضير" },
    { en: "Tamtert", ar: "تامترت" },
    { en: "Timoudi", ar: "تيمودي" },
  ],
  "53": [
    { en: "Ain Salah", ar: "عين صالح" },
    { en: "Foggaret Ezzoua", ar: "فقارة الزوى" },
    { en: "Inghar", ar: "إينغر" },
  ],
  "54": [
    { en: "Ain Guezzam", ar: "عين قزام" },
    { en: "Tin Zouatine", ar: "تين زواتين" },
  ],
  "55": [
    { en: "Benaceur", ar: "بن ناصر" },
    { en: "Blidet Amor", ar: "بلدة اعمر" },
    { en: "El Alia", ar: "العالية" },
    { en: "El-Hadjira", ar: "الحجيرة" },
    { en: "M'naguer", ar: "المنقر" },
    { en: "Megarine", ar: "المقارين" },
    { en: "Nezla", ar: "النزلة" },
    { en: "Sidi Slimane", ar: "سيدي سليمان" },
    { en: "Taibet", ar: "الطيبات" },
    { en: "Tebesbest", ar: "تبسبست" },
    { en: "Temacine", ar: "تماسين" },
    { en: "Touggourt", ar: "تقرت" },
    { en: "Zaouia El Abidia", ar: "الزاوية العابدية" },
  ],
  "56": [
    { en: "Bordj El Haouass", ar: "برج الحواس" },
    { en: "Djanet", ar: "جانت" },
  ],
  "57": [
    { en: "Djamaa", ar: "جامعة" },
    { en: "El-M'ghaier", ar: "المغير" },
    { en: "M'rara", ar: "المرارة" },
    { en: "Oum Touyour", ar: "أم الطيور" },
    { en: "Sidi Amrane", ar: "سيدي عمران" },
    { en: "Sidi Khelil", ar: "سيدي خليل" },
    { en: "Still", ar: "سطيل" },
    { en: "Tenedla", ar: "تندلة" },
  ],
  "58": [
    { en: "El Meniaa", ar: "المنيعة" },
    { en: "Hassi Fehal", ar: "حاسي الفحل" },
    { en: "Hassi Gara", ar: "حاسي القارة" },
  ],
};
