export type WilayaInfo = { code: string; en: string; ar: string };

export const WILAYAS: WilayaInfo[] = [
  { code: "01", en: "Adrar", ar: "أدرار" },
  { code: "02", en: "Chlef", ar: "الشلف" },
  { code: "03", en: "Laghouat", ar: "الأغواط" },
  { code: "04", en: "Oum El Bouaghi", ar: "أم البواقي" },
  { code: "05", en: "Batna", ar: "باتنة" },
  { code: "06", en: "Béjaïa", ar: "بجاية" },
  { code: "07", en: "Biskra", ar: "بسكرة" },
  { code: "08", en: "Béchar", ar: "بشار" },
  { code: "09", en: "Blida", ar: "البليدة" },
  { code: "10", en: "Bouira", ar: "البويرة" },
  { code: "11", en: "Tamanrasset", ar: "تمنراست" },
  { code: "12", en: "Tébessa", ar: "تبسة" },
  { code: "13", en: "Tlemcen", ar: "تلمسان" },
  { code: "14", en: "Tiaret", ar: "تيارت" },
  { code: "15", en: "Tizi Ouzou", ar: "تيزي وزو" },
  { code: "16", en: "Alger", ar: "الجزائر" },
  { code: "17", en: "Djelfa", ar: "الجلفة" },
  { code: "18", en: "Jijel", ar: "جيجل" },
  { code: "19", en: "Sétif", ar: "سطيف" },
  { code: "20", en: "Saïda", ar: "سعيدة" },
  { code: "21", en: "Skikda", ar: "سكيكدة" },
  { code: "22", en: "Sidi Bel Abbès", ar: "سيدي بلعباس" },
  { code: "23", en: "Annaba", ar: "عنابة" },
  { code: "24", en: "Guelma", ar: "قالمة" },
  { code: "25", en: "Constantine", ar: "قسنطينة" },
  { code: "26", en: "Médéa", ar: "المدية" },
  { code: "27", en: "Mostaganem", ar: "مستغانم" },
  { code: "28", en: "M'Sila", ar: "المسيلة" },
  { code: "29", en: "Mascara", ar: "معسكر" },
  { code: "30", en: "Ouargla", ar: "ورقلة" },
  { code: "31", en: "Oran", ar: "وهران" },
  { code: "32", en: "El Bayadh", ar: "البيض" },
  { code: "33", en: "Illizi", ar: "إليزي" },
  { code: "34", en: "Bordj Bou Arréridj", ar: "برج بوعريريج" },
  { code: "35", en: "Boumerdès", ar: "بومرداس" },
  { code: "36", en: "El Tarf", ar: "الطارف" },
  { code: "37", en: "Tindouf", ar: "تندوف" },
  { code: "38", en: "Tissemsilt", ar: "تيسمسيلت" },
  { code: "39", en: "El Oued", ar: "الوادي" },
  { code: "40", en: "Khenchela", ar: "خنشلة" },
  { code: "41", en: "Souk Ahras", ar: "سوق أهراس" },
  { code: "42", en: "Tipaza", ar: "تيبازة" },
  { code: "43", en: "Mila", ar: "ميلة" },
  { code: "44", en: "Aïn Defla", ar: "عين الدفلى" },
  { code: "45", en: "Naâma", ar: "النعامة" },
  { code: "46", en: "Aïn Témouchent", ar: "عين تموشنت" },
  { code: "47", en: "Ghardaïa", ar: "غرداية" },
  { code: "48", en: "Relizane", ar: "غليزان" },
  { code: "49", en: "Timimoun", ar: "تيميمون" },
  { code: "50", en: "Bordj Badji Mokhtar", ar: "برج باجي مختار" },
  { code: "51", en: "Ouled Djellal", ar: "أولاد جلال" },
  { code: "52", en: "Béni Abbès", ar: "بني عباس" },
  { code: "53", en: "In Salah", ar: "عين صالح" },
  { code: "54", en: "In Guezzam", ar: "عين قزام" },
  { code: "55", en: "Touggourt", ar: "تقرت" },
  { code: "56", en: "Djanet", ar: "جانت" },
  { code: "57", en: "El M'Ghair", ar: "المغير" },
  { code: "58", en: "El Meniaa", ar: "المنيعة" },
];

export const WILAYA_BY_NAME: Record<string, WilayaInfo> = Object.fromEntries(
  WILAYAS.map((w) => [w.en, w])
);

export const WILAYA_BY_CODE: Record<string, WilayaInfo> = Object.fromEntries(
  WILAYAS.map((w) => [w.code, w])
);
